export interface IUpdateNfeDTO {
  id?: string
  cliente: string
  fornecedor?: string
  data: Date
  tipo: string
  transpNome?: string
  frete: number
  seguro: number
  outrasDespesas: number
  freteOutros: number
  desconto: number
  totalCheque?: number
  totalDinheiro: number
  totalCartaoCredito?: number
  totalBoleto?: number
  totalOutros?: number
  totalCartaoDebito?: number
  totalNota?: number
  totalProduto?: number
  serie: number
  estorno?: boolean
  complementar?: boolean
  naturezaOp: string
  observacoes?: string
  idCountry: number
  descCountry: string
  nDi?: string
  dDi?: Date
  xLocDesemb?: string
  uFDesemb?: string
  tpViaTransp?: number
  cExportador?: string
  transportador?: string
  erros?: string
  products: any[]
  companyId: string
  paymentMethodId: string
  Customer?: any
  orderId?: string
  customerApoioId?: string
  customerApoioName?: string
  cpfCnpjApoio?: string
  employeeId: string
}
